@startuml fsio_lib_logging_fsio_loggingfsio_renamefile

title Activity Diagram of the Class Method LoggingFSIO.renameFile()

start

:<b>Source</b> - string, relative or absolute path to the source file
<b>Name</b> - string, the new base name of the file<

if (is <b>Source</b> not a string?) then (True)
    :<b>iError</b> = 1,
    <b>strError</b> is formed
    correspondingly;
    
    :Log @ERROR <b>strError</b> ;
elseif (is <b>Source</b> not a path\nto an existing file?) then (True)
    :<b>iError</b> = 2,
    <b>strError</b> is formed
    correspondingly;
    
    :Log @ERROR <b>strError</b> ;
elseif (is <b>Name</b> not a string?) then (True)
    :<b>iError</b> = 1,
    <b>strError</b> is formed
    correspondingly;
    
    :Log @ERROR <b>strError</b> ;
else (No)
    if (<b>Name</b> is not a base file name?) then (True)
        :<b>iError</b> = 2,
        <b>strError</b> is formed
        correspondingly;
    
        :Log @ERROR <b>strError</b> ;
    else (False)
        :extract the folder name (dirname())
        from the <b>Source</b> path;
        
        :try to rename the file by copying it with
        the new base name within the same
        folder and deleting the original file
        using method <b>moveFile</b>()
        -> <b>iError, strError</b> pair|
        
        if (error occured,\n<b>iError</b> > 0?) then (Yes)
            :Log @Error
            <b>strError</b> ;
        else (No)
            :Log @DEBUG that
            the file is renamed;
        endif
    endif
endif

:return <b>iError, strError</b> pair>

stop

@enduml